services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@db:5432/techtreadsdb
    depends_on:
      - db
    networks:
      - techtreads-network
    ports:
      - "3000:3000"

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=techtreadsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - techtreads-network
    ports:
      - "5432:5432"

networks:
  techtreads-network:
    driver: bridge

volumes:
  postgres-data:
