services:
  - type: web
    name: techtreads-backend
    env: node
    plan: free
    buildCommand: bun install && bun run build && bun run db:push
    startCommand: bun run start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: techtreads-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  - name: techtreads-db
    databaseName: techtreadsdb
    user: techtreads_user
    plan: free
